services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
    environment:
      SERVER_NAME: localhost:443
      DATABASE_URL: postgresql://${POSTGRES_USER:-app_user}:${POSTGRES_PASSWORD:-app_password}@database:5432/${POSTGRES_DATABASE:-app_base}?serverVersion=16&charset=utf8
      MAILER_DSN: smtp://mailhog:1025
    tty: true
    depends_on:
      - database
      - mailhog
    volumes:
      - $PWD/:/app
      - $PWD/vendor:/app/vendor
    ports:
      - "8080:80"
      - "443:443"

  database:
    image: postgres:15.15
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-app_base}
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_password}
    volumes:
      - $PWD/docker/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
